### ISSUE TITLE
Using the bin2txt function with a string that contains spaces breaks the output

### ISSUE THREAD

**Issue by Paradoxis** [mkzero/d3coder#5]
When parsing a binary string that contains spaces/newlines like the following:

    01001000 01100101 01101100 01101100 
    01101111 00100000 01110111 01101111 
    01110010 01101100 01100100 

The function returns the following string:

    H²Û-|ïoÜ­@

Instead of:

    Hello world

**Comment by mkzero** [comment]
Thanks for the PR, just pushed it to the webstore.
